# Generated by Django 4.2.18 on 2025-02-04 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_code', models.CharField(max_length=10, unique=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('coordinates', models.JSONField()),
                ('timezone', models.CharField(max_length=50)),
                ('unlocs', models.JSONField()),
                ('alias', models.JSONField(default=list)),
                ('regions', models.JSONField(default=list)),
            ],
        ),
    ]
